
image_server:
  storage_path: ${user.home}/files/storage
  zoom_path: ${user.home}/files/zoom
  index: index.html
  enable_filename: true

multipart:
  maxFileSize: -1
  maxRequestSize: -1
spring:
  http:
    multipart:
      max-file-size: -1