
image-server:
  master-storage:
    type: file
    file:
      path: ${user.home}/files/storage
  thumbnail-storage:
    type: file
    file:
      path: ${user.home}/files/zoom
  index: index.html
  enable-filename: true

multipart:
  maxFileSize: -1
  maxRequestSize: -1
spring:
  http:
    multipart:
      max-file-size: -1
      max-request-size: -1